title: Sarah Thompson — AI E-Portfolio
description: Modules, units, and artefacts for my Master's in AI
theme: jekyll-theme-cayman
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default